### ISSUE TITLE
Honeypot field is not hidden

### ISSUE THREAD

**Issue by Ruxter** [nucleos/NucleosAntiSpamBundle#140]
Hi,
I am using Symfony and want to use your bundle.
I have a form and I added this as third parameter to createForm method:
```
array(
        'antispam_time' => true,
        'antispam_time_min' => 10,
        'antispam_time_max' => 60,
    
        // Honeypot protection
        'antispam_honeypot'       => true,
        'antispam_honeypot_class' => 'hidden',
        'antispam_honeypot_field' => 'email')
```
As I can see the field is added, but is not hidden (it's visible).
I added also this to CSS:
```
.hidden{ 
  display:none; 
}
```

But the honeypot field is still visible at the end of form. In debugger I can see:
`<input type="text" id="form_email" name="form[email]" class="hidden form-control">`

Or if I add this to the config/packages/nucleos_antispam.yaml
```
nucleos_antispam:
# Time protection
    time:
        min: 5
        max: 3600
        global: true

    # Honeypot protection
    honeypot:
        field: 'email'
        class: 'hidden'
        global: true
        provider: 'nucleos_antispam.provider.session'
```
It seems it does nothing (I can't see the field via debugger)

How can I fix that?
Many thanks
